FROM node:20-alpine AS builder
WORKDIR /server
COPY . .
RUN npm install
RUN npm run build
FROM node:20-alpine AS runner
WORKDIR /server
COPY --from=builder /server/dist/bundle.js ./
COPY --from=builder /server/package.json ./
COPY --from=builder /server/node_modules ./node_modules
EXPOSE 8000
CMD [ "node", "bundle.js" ]