FROM node:20-alpine AS builder
WORKDIR /client
COPY . .
RUN npm install
RUN npm run build
FROM node:20-alpine AS runner
WORKDIR /client
COPY --from=builder /client/.next ./.next
COPY --from=builder /client/public ./public
COPY --from=builder /client/package.json ./
COPY --from=builder /client/node_modules ./node_modules
EXPOSE 3000
CMD ["npm", "run","start"]